// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVASvOtnWRVCoy4TzchKpW1w1yfJezB90',
    appId: '1:599868749797:web:1556ebe50b9028dd6b210c',
    messagingSenderId: '599868749797',
    projectId: 'avivamiento-6351c',
    authDomain: 'avivamiento-6351c.firebaseapp.com',
    databaseURL: 'https://avivamiento-6351c-default-rtdb.firebaseio.com',
    storageBucket: 'avivamiento-6351c.appspot.com',
    measurementId: 'G-WDK3E5VLBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSO1MepnInoP3LpcJ3R_GC6ds_3ImNag',
    appId: '1:599868749797:android:79b1a2c1f1a89bd66b210c',
    messagingSenderId: '599868749797',
    projectId: 'avivamiento-6351c',
    databaseURL: 'https://avivamiento-6351c-default-rtdb.firebaseio.com',
    storageBucket: 'avivamiento-6351c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfMWu3uJCM4Y-epjxN_bsqcwy97wRJPs',
    appId: '1:599868749797:ios:c446a19d6c6c74e36b210c',
    messagingSenderId: '599868749797',
    projectId: 'avivamiento-6351c',
    databaseURL: 'https://avivamiento-6351c-default-rtdb.firebaseio.com',
    storageBucket: 'avivamiento-6351c.appspot.com',
    iosClientId:
        '599868749797-7rmfrbabn8vbc1uj8ilgufvgi0rfuvhn.apps.googleusercontent.com',
    iosBundleId: 'com.iglesia.avivamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfMWu3uJCM4Y-epjxN_bsqcwy97wRJPs',
    appId: '1:599868749797:ios:c446a19d6c6c74e36b210c',
    messagingSenderId: '599868749797',
    projectId: 'avivamiento-6351c',
    databaseURL: 'https://avivamiento-6351c-default-rtdb.firebaseio.com',
    storageBucket: 'avivamiento-6351c.appspot.com',
    iosClientId:
        '599868749797-7rmfrbabn8vbc1uj8ilgufvgi0rfuvhn.apps.googleusercontent.com',
    iosBundleId: 'com.iglesia.avivamiento',
  );
}
